//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTODAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrera
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string campus { get; set; }
        public string tipo { get; set; }
        public int duracion { get; set; }
    }
}
