//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTODAS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uniwebsiteEntities : DbContext
    {
        public uniwebsiteEntities()
            : base("name=uniwebsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carrera> carreras { get; set; }
        public virtual DbSet<consulta> consultas { get; set; }
        public virtual DbSet<noticia> noticias { get; set; }

        public System.Data.Entity.DbSet<PROYECTODAS.Models.CarreraClass> CarreraClasses { get; set; }
    }
}
