//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTODAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticia
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string cuerpo { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
